spring:
  profiles:
    active: node3

# 全局配置
settings:
  # 因为 tio 配置的初始同步节点都没有启动，所以一直抛出连接超时的异常，其实这并不影响系统运行，
  # 在这里增加这配置，默认部署成单节点，不同步数据。
  node-discover: true
  # 发生交易时是否自动挖矿
  auto-mining: true

# 关闭 tio 日志
logging:
  level:
    org:
      tio:
        server: OFF
        client: OFF

#devtools:
#  restart:
#    enabled: true  #支持热部署